spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          url:https://github.com/lupsi12/cursor_projects.git
          default-label: master
          search-paths: 
            - configuratins/
            - configurations/{application}

server:
  port: 8787
