spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          url:
          default-label: master
          search-paths: 
            - configuratins/
            -configurations/{application}

server:
  port: 8787